# Dockerfile for bot development image
FROM python:3.12.2-slim-bookworm

WORKDIR /bot

COPY requirements.txt .

# Install project dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Install git
RUN apt-get -y update
RUN apt-get -y install git

# Copy root directory
COPY . .

CMD ["/bin/bash"]