FROM python:3.12.6-slim

WORKDIR /bot

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN apt-get -y update
RUN apt-get -y install git

COPY . .

EXPOSE 8000

ENV BOT_MODE="dev"

CMD ["/bin/bash"]