FROM python:3.13.3-slim

WORKDIR /bot
COPY requirements.txt .

RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

COPY . .

ARG PORT=8000
EXPOSE $PORT

ENV PORT=$PORT
ENV HOST=0.0.0.0
ENV BOT_MODE=prod

RUN chmod +x start_prod.sh
CMD ["./start_prod.sh"]