services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: pelis-bot
    container_name: pelis-container
    volumes:
      - .:/bot
    command: "/bin/bash"
    stdin_open: true
    tty: true