services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: themoviebot
    container_name: themoviebot
    ports:
      - 8000:8000
    volumes:
      - .:/bot
    command: "/bin/bash"
    stdin_open: true
    tty: true