FROM python:3.12.6-slim

WORKDIR /bot

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

EXPOSE 8000

RUN chmod +x start_prod

ENV BOT_MODE="prod"

CMD ["./start_prod"]